index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }
temp:
    path:      /temp
    defaults:  { _controller: AppBundle:Default:temp }
create_pag:
    path:      /createpag
    defaults:  { _controller: AppBundle:CreatePag:index }
select_pag:
    path:      /editpag
    defaults:  { _controller: AppBundle:EditPag:index }
edit_pag:
    path:      /editpag/{pag}
    defaults:  { _controller: AppBundle:EditPag:edit }    
load_pag:
    path:      /loadpag/{pag}/{action}
    defaults:  { _controller: AppBundle:LoadPag:index }
delete_pag:
    path:      /deletepag
    defaults:  { _controller: AppBundle:DeletePag:index }
frame_load:
    path:      /frameload/{pag}/{action}
    defaults:  { _controller: AppBundle:FrameLoad:index }
list_obj:
    path:     /listobj/{pag}
    defaults: { _controller: AppBundle:ListObj:index }
ajax_del:
    path:     /ajaxdel/{pag}
    defaults: { _controller: AppBundle:AjaxDel:index }
ajax_mod:
    path:     /ajaxmod/{pag}
    defaults: { _controller: AppBundle:AjaxMod:index }
ajaxprocess:
    path:     /ajaxprocess
    defaults: { _controller: AppBundle:AjaxMod:mod }
ajax_add:
    path:     /ajaxadd/{pag}
    defaults: { _controller: AppBundle:AjaxAdd:index }