index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }
create_pag:
    path:      /createpag
    defaults:  { _controller: AppBundle:CreatePag:index }
edit_pag:
    path:      /editpag
    defaults:  { _controller: AppBundle:EditPag:index }
load_pag:
    path:      /loadpag/{pag}
    defaults:  { _controller: AppBundle:LoadPag:index }
delete_pag:
    path:      /deletepag
    defaults:  { _controller: AppBundle:DeletePag:index }
frame_load:
    path:      /frameload/{pag}
    defaults:  { _controller: AppBundle:FrameLoad:index }
list_obj:
    path:     /listobj/{pag}
    defaults: { _controller: AppBundle:ListObj:index }
