index:
    defaults:  { _controller: AppBundle:Default:index }
    path:      /
create_pag:
    defaults:  { _controller: AppBundle:CreatePag:index }
    path:      /createpag
edit_pag:
    defaults:  { _controller: AppBundle:EditPag:index }
    path:      /editpag
load_pag:
    defaults:  { _controller: AppBundle:LoadPag:index }
    path:      /loadpag/{pag}
delete_pag:
    defaults:  { _controller: AppBundle:DeletePag:index }
    path:      /deletepag
frame_load:
    defaults:  { _controller: AppBundle:FrameLoad:index }
    path:      /frameload/{pag}