index:
    defaults:  { _controller: AppBundle:Default:index }
    path:      /
create_pag:
    defaults:  { _controller: AppBundle:CreatePag:index }
    path:      /createpag
edit_pag:
    defaults:  { _controller: AppBundle:EditPag:index }
    path:      /editpag
delete_pag:
    defaults:  { _controller: AppBundle:DeletePag:index }
    path:      /deletepag    